require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
Metrics/LineLength:
  Max: 163
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:  
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Style/GuardClause:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false