default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: psql
  pool: 5

production:
  <<: *default
  database: SoftwareG6_production

development:
  <<: *default
  database: SoftwareG6_development

test:
  <<: *default
  database: SoftwareG6_test